### PR TITLE
[rv32im] Add .travis.yml

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by samuelgruetter** [comment]
The travis build fails, but I don't understand why. The end of the [log](https://travis-ci.com/github/mit-plv/kami/jobs/299264405) is:

```
make[1]: Leaving directory `/home/travis/build/mit-plv/kami'
The command "make" exited with 0.
Done. Your build exited with 1.
```

**Comment by JasonGross** [comment]
Searching the build log for "error" gives
```
File "/home/travis/build/mit-plv/riscv-coq/src/riscv/Spec/Decode.v", line 24, characters 8-23:
Error: Cannot find a physical path bound to logical path matching suffix
Utility.
make[2]: *** [/home/travis/build/mit-plv/riscv-coq/src/riscv/Spec/Decode.vo] Error 1
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/travis/build/mit-plv/riscv-coq'
make: *** [spec] Error 2
make: Leaving directory `/home/travis/build/mit-plv/riscv-coq'
The command "(cd .. && git clone https://github.com/mit-plv/riscv-coq.git && make -C riscv-coq)" exited with 2.
```
The travis build has three invocations of `make`.  One fails, the other two succeed.  If you want to be resiliant to build failures in the dependencies that don't impact kami, you can add `|| true` at the end of the first two lines

**Comment by samuelgruetter** [comment]
Oh so you're building coqutil and riscv-coq as well. I thought kami does not depend on them, so they don't need to be built here?

**Comment by JasonGross** [comment]
Ah, it looks like it no longer builds them since https://github.com/mit-plv/kami/commit/d4da390550dcb2c23f4fcda03594182d89c7d8c8 , which was after I initially made the PRs, and I didn't reevaluate my assumptions.  So you can just delete the relevant lines from .travis.yml

**Pull request merged**
