### PR TITLE
Overlay for Coq PR #9918 fixing template-polymorphism bug

### PR DESCRIPTION
**Pull request by mattam82**
If I'm not mistaken this is what bedrock2 points to in Coq's master CI. PR for coq/coq#9918

### CODE REVIEW

**Comment by samuelgruetter** [comment]
@joonwonc are you ok with this? Apparently this is needed to make bedrock2 work.

**Comment by joonwonc** [comment]
Looks good to me, but let me try to compile first whether this change does not make any errors.
After then I will apply the change and close the PR.

**Comment by mattam82** [comment]
Note that the idea is to make Attribute and Vec template-polymorphic, so that they appear as they would in the previous version after section closing.

**Comment by mattam82** [comment]
And it’s been tested through Coq’s CI, so should be fine :) But you never know after a rebase

**Comment by joonwonc** [comment]
Thanks! I understood the change and confirmed it successfully compiles.
Let me merge right now.

**Pull request merged**
